import '../styles/globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { ThemeProvider } from '../context/ThemeContext';

// Prevent Font Awesome from adding its CSS since we did it manually above
config.autoAddCss = false;

/**
 * Wraps the incoming page component with the application ThemeProvider.
 *
 * @param {Object} props - Props passed to the custom App component.
 * @param {import('react').ComponentType<any>} props.Component - The page component to render.
 * @param {Object} props.pageProps - Props to be forwarded to the page component.
 * @returns {JSX.Element} The root JSX element that renders the page inside ThemeProvider.
 *
 * Auto-generated by CodeRabbit.
 */
function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default MyApp;